In [46]:
import numpy as np
import time

In [40]:
x = np.array([3, 1, 10,5,9,7,23])
x

array([ 3,  1, 10,  5,  9,  7, 23])

In [41]:
# return the values of first 32smallest element
np.partition(x,2)
# only first 2 elmenet are sorted , rest are not guaranteed 

array([ 1,  3,  5, 10,  9,  7, 23])

In [42]:
# returns the index of first 2 smallest element in given array
np.argpartition(x,2)

array([1, 0, 3, 2, 4, 5, 6])

In [45]:
# returns the index of largest 2 element in given array,  negative indexing for last 2
np.argpartition(x,-2)

array([1, 0, 3, 5, 4, 2, 6])

In [37]:
# fetch only last 2 index and sort 
np.sort(np.argpartition(x,-2)[-2:])

array([2, 4])

In [39]:
# argsort will sort the entire array and return ths sorted array
np.argsort(x)

array([6, 1, 0, 3, 5, 4, 2])

In [13]:
# lets generate array using random distribution
x=np.random.randn(100000000)

In [18]:
x

array([-0.24993635, -1.18929223,  0.87018946, ...,  0.26446444,
        0.15007473, -0.70169414])

In [14]:
start=time.time()
np.sort(np.argpartition(x,-5)[-5:])
end=time.time()

In [15]:
end-start

1.7959208488464355

In [16]:
start=time.time()
np.argsort(x)[-5:]
end=time.time()

In [17]:
end-start

27.581597089767456

In [74]:
import time
start=time.time()
end=time.time()

1600371274.435649

In [ ]:
# clearly argpartition perform better ,if we have huge dataset and we need to identify top 10 item,
# we can go with argpartition instead of argsort